name:   Performing Learning tasks
on:     workflow_dispatch
jobs:
    task1:
        name:   Checkout new branch
        runs-on:    ubuntu-latest
        steps:
            -   name:   Get Code
                uses:   actions/checkout@v4
            -   name: Checking out new branch named test
                run:    |
                    git checkout -b test
    task2:
        name:   Creating a text file
        runs-on:    ubuntu-latest
        steps:
            -   name:	Create new text file
                shell:  bash
                run:    |
                    echo -e "GitHub Actions is a continuous integration and continuous delivery
                     (CI/CD) platform that allows you to automate your build, test, and deployment
                     pipeline.\n You can create workflows that build and test every pull request 
                     to your repository, or deploy merged pull requests to production." >> Github_actions_overview.txt
            -   name:   Uploading the Overview file
                uses:   actions/upload-artifact@v3
                with:
                    name:   Overview_GithubActions
                    path:   Github_actions_overview.txt
            -   name:	Downloading the Overview file
                uses:	actions/download-artifact@v3
                with:
                    name:	Overview_GithubActions
            -   name: Printing the text file
                run:	|
                    echo cat Github_actions_overview.txt
    task3:
        name:   Creating a variable
        runs-on:    ubuntu-latest
        env:
            Greeting:   Good Afternoon
        outputs:
            out1:   ${{env.Greeting}}
        steps:
            -   name:   Printing the variable
                id: step1
                run:    echo "The value of the variable Greeting is => $Greeting"
    task4:
        name:   Using previously created variable
        needs:  task3
        runs-on:    ubuntu-latest
        steps:
            -   name:   Use variable from other job
                run:    echo "The variable used in task3 was = ${{needs.task3.outputs.out1}}"